//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisesYPlatillos {
	
	
	public partial class Default2 {
		
		protected System.Web.UI.WebControls.TextBox movieTitle;
		
		protected System.Web.UI.WebControls.TextBox movieGenre;
		
		protected System.Web.UI.WebControls.Button btnAdd;
		
		protected System.Web.UI.WebControls.DataGrid Grid;
		
		protected System.Web.UI.WebControls.Label lbl;
		
		protected System.Web.UI.WebControls.TextBox movieId;
		
		protected System.Web.UI.WebControls.Button deleteMovie;
		
		protected System.Web.UI.WebControls.Label lbll;
		
		protected System.Web.UI.WebControls.TextBox gmovieId;
		
		protected System.Web.UI.WebControls.TextBox gmovieGenre;
		
		protected System.Web.UI.WebControls.TextBox gmovieTitle;
		
		protected System.Web.UI.WebControls.Button editMovie;
	}
}
