//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisesYPlatillos {
    
    
    public partial class Default {
        
        protected System.Web.UI.WebControls.TextBox txtComida;
        
        protected System.Web.UI.WebControls.DropDownList cboPais;
        
        protected System.Web.UI.WebControls.Button btnAdd;
        
        protected System.Web.UI.WebControls.DataGrid Grid;
        
        protected System.Web.UI.WebControls.Label lbl;
        
        protected System.Web.UI.WebControls.TextBox saucerId;
        
        protected System.Web.UI.WebControls.Button deleteSaucer;
        
        protected System.Web.UI.WebControls.Label idpelicula;
        
        protected System.Web.UI.WebControls.TextBox eSaucerId;
        
        protected System.Web.UI.WebControls.TextBox eSaucerName;
        
        protected System.Web.UI.WebControls.DropDownList cbaPais;
        
        protected System.Web.UI.WebControls.Button editSaucer;
    }
}
