//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisesYPlatillos {
	
	
	public partial class testContentPlaceHolder {
		
		protected System.Web.UI.WebControls.TextBox txtComida;
		
		protected System.Web.UI.WebControls.DropDownList cboPais;
		
		protected System.Web.UI.WebControls.DataGrid Grid;
		
		protected System.Web.UI.WebControls.Button btnAgregar;
		
		protected System.Web.UI.WebControls.Button btnEliminar;
		
		protected System.Web.UI.WebControls.Button btnEditar;
	}
}
