//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oficial2 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbla;
		
		protected System.Web.UI.WebControls.TextBox txta;
		
		protected System.Web.UI.WebControls.Label lblb;
		
		protected System.Web.UI.WebControls.TextBox txtb;
		
		protected System.Web.UI.WebControls.Label lblc;
		
		protected System.Web.UI.WebControls.TextBox txtc;
		
		protected System.Web.UI.WebControls.Button solve;
		
		protected System.Web.UI.WebControls.Button @new;
	}
}
