//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oficial2
{
	using System;
	using System.Web;
	using System.Web.UI;

	public partial class Default : System.Web.UI.Page
	{

		public void btnsolve(object sender, EventArgs aa){
			int a,b,c;
			string aaa,bb,cc;
			double x1,x2;
			aaa = txta.Text;
			bb = txtb.Text;
			cc = txtc.Text;
			a = Convert.ToInt32 (aaa);
			b = Convert.ToInt32 (bb);
			c = Convert.ToInt32 (cc);
			x1=(-b + Math.Sqrt((b*b) -4 * a * c)) / (2*a);
			x2=(-b - Math.Sqrt((b*b) -4 * a * c)) / (2*a);

			Response.Write("<br/>");
			Response.Write("X1= " + x1);
			Response.Write("<br/>");
			Response.Write("X2= " + x2);
		}
		public void btnnew(object sender , EventArgs e){
			Response.Redirect ("pagina2.aspx");
		}

		private float fx1(int a, int b, int c){
			return (float)  (-b + Math.Sqrt((b*b) -4 * a * c)) / (2*a);
		}

		private float fx2(int a, int b, int c){
			return (float)  (-b - Math.Sqrt((b*b) -4 * a * c)) / (2*a);
		}




	}
}

